### ISSUE TITLE
Discuss/Document Procedures for Deploying Changes

### ISSUE THREAD

**Issue by SCasarottoDDS** [deptofdefense/dds.mil#103]
As we get closer to the end of setting up v2, we should discuss what procures are appropriate for content and other code releases on this repo. There are security measures that can be added to require an approver to get anything into production. This produces more security by may be annoying for simple copy changes. Like most security discussions, there is a spectrum here and not necessarily one right answer. We can discuss and see what we think makes the most sense for DDS in its current form and planning for the future

**Comment by SCasarottoDDS** [comment]
This feels like another good opportunity to use this https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md and document our decision in the wiki. This will actually relate to #40 some.

**Comment by jhackshaw-dds** [comment]
https://github.com/deptofdefense/dds.mil/wiki/ADR:-Release-Process
