### ISSUE TITLE
search feature

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#137]
<img width="966" alt="Screen Shot 2020-05-06 at 9 22 47 AM" src="https://user-images.githubusercontent.com/62910835/81182010-420b2f00-8f7b-11ea-8682-853410967413.png">

**Comment by jhackshaw-dds** [comment]
Search has been added - based on some limitations in search.gov the current form redirects to their site for results which we have very little control over.

With more content and the site moved to the main dds.mil domain, we should be able render the results ourselves.
