### ISSUE TITLE
Ensure all photos are as good as possible for MVP and consent forms are filled

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#200]
a/c
- all photos are approved 
- all consent forms are collected and stored on drive

**Comment by SCasarottoDDS** [comment]
About Page: https://v2-master--dds-mil.netlify.app/about
- Header
- Possible in the image bar (4th image)

Team Page: https://v2-master--dds-mil.netlify.app/team
- Header

Join Page: https://v2-master--dds-mil.netlify.app/join-us
- Possible in the image bar (4th image)
