### ISSUE TITLE
make consent form for photos

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#201]
work with phil to make sure we are good in the eyes of the law

**Comment by racheldds** [comment]
Draft form here: https://docs.google.com/document/d/1yMgKn8pYiDsMPyfEwpflnBpsKmdgdRiYqufw-gHCA-Y/edit?usp=sharing

@ashhath01 let me know if you'd like me to share with Phil for his review.

**Comment by ashhath01** [comment]
closing w/ review done and approved
