### ISSUE TITLE
cj blog post v1

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#205]
create google doc with rough outline of blog post
work w/ rachel to copy write

deadline approx 1 week

**Comment by racheldds** [comment]
https://docs.google.com/document/d/1NxYAyE1pzVwE8ncCU9RBVxHvulEg1MYLTRvFK2zdPws/edit

Drafted by CJ/reviewed by Rachel

Ready to publish via CMS, but need to coord on photo
