### ISSUE TITLE
design feedback

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#279]
After reviewing via desktop (across browsers), iPad, and iPhone, the only two (extremely minor - TINY, even!) considerations remaining from my list are:

h3 line-height (All viewports, https://v2-master--dds-mil.netlify.app/work/product-development): Currently looks vertically compressed. By adopting an increased line-height similar to that used on other elements across the site produces something like this (1.3: https://a.cl.ly/BluZAOw7, 1.6: https://a.cl.ly/E0ubvzX0). Same on mobile (current: https://a.cl.ly/4guyEjWR and then using 1.3: https://a.cl.ly/8LujK7Nk)

"Official website" banner (Mobile, all pages): Currently appears as https://a.cl.ly/5zu1qXO2, adding some vertical margin/padding gives it a bit of breathing room (https://a.cl.ly/8LujK7l4)

Performance, functionality, content, and accessibility are on point 💪

Forgot one item: Banner scaling on home page (Desktop): https://a.cl.ly/NQuDXre5. 

This is reproducible when the viewport height is increased (on portrait and/or large monitors) and can likely easily be vertically constrained.

**Comment by jhackshaw-dds** [comment]
Banner scaling, official website padding, and line height were all updated in #280
