### ISSUE TITLE
dds.mil feedback from slack

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#304]
Can we add an optional "GitHub Profile" text field to the join page?  Since we are asking for LinkedIn.

Probably worth mentioning on the Join Us page, that we are open to Detailees from other agencies, and Military Active Duty and being more specific about the pathways to join.

Also, I'm not sure MySymptoms.Mil is "firefighting", but maybe I can save those comments for the vision/all hands?

**Comment by ashhath01** [comment]
<img width="911" alt="Screen Shot 2020-05-21 at 3 05 49 PM" src="https://user-images.githubusercontent.com/62910835/82596019-9e25a400-9b74-11ea-8075-9323656be264.png">
<img width="594" alt="Screen Shot 2020-05-21 at 3 02 18 PM" src="https://user-images.githubusercontent.com/62910835/82596036-a54cb200-9b74-11ea-9050-16e8d4507b57.png">
<img width="905" alt="Screen Shot 2020-05-21 at 3 05 32 PM" src="https://user-images.githubusercontent.com/62910835/82596043-a7af0c00-9b74-11ea-80dd-1814d7f382e5.png">
<img width="561" alt="Screen Shot 2020-05-21 at 3 05 59 PM" src="https://user-images.githubusercontent.com/62910835/82596049-aa116600-9b74-11ea-8410-b189a926e43c.png">
<img width="919" alt="Screen Shot 2020-05-21 at 3 06 46 PM" src="https://user-images.githubusercontent.com/62910835/82596073-b695be80-9b74-11ea-9448-6c05a8f860b5.png">

**Comment by ashhath01** [comment]
<img width="914" alt="Screen Shot 2020-05-25 at 10 22 33 AM" src="https://user-images.githubusercontent.com/62910835/82903646-3df58000-9f2f-11ea-98e7-971c040f76aa.png">

**Comment by jhackshaw-dds** [comment]
I believe all of the issues mentioned here have been handled, particularly font kerning/boldness/spacing in markdown content. Github profile was added, but no longer really applies. Content was updated as well.
