### ISSUE TITLE
Change MTA-STS to enforced

### ISSUE THREAD

**Issue by paultag-gov** [deptofdefense/dds.mil#32]

**Comment by paultag-gov** [comment]
![mta-sts](https://user-images.githubusercontent.com/25226264/56763138-9f1cb400-676f-11e9-9396-042b6552dfda.png)

**Comment by jordangov** [comment]
And how do we do this? :)

**Comment by paultag-gov** [comment]
Too early

**Comment by jordangov** [comment]
You're too early.
