### ISSUE TITLE
Update topics on site for search purposes

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [deptofdefense/dds.mil#374]
I am trying to create a [site](https://github.com/its-a-lisa-at-work/sbom) using the [Gatsby template](https://github.com/18F/federalist-uswds-gatsby) from [Federalist](https://federalist.18f.gov/) that leverages the [USWDS](https://designsystem.digital.gov/). This site is one of the very few that I found that is also made with Gatsby and USWDS so I suggest updating the [topic](https://docs.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics) on the site so that it shows up in future [searches](https://github.com/search?q=topic%3Agatsby+topic%3Auswds&type=Repositories).

**Comment by jhackshaw-dds** [comment]
This is excellent feedback, thank you! I've added the Gatsby, USWDS, and netlify-cms as topics.

**Comment by its-a-lisa-at-work** [comment]
Wonderful, thanks!!
