### ISSUE TITLE
Add site to DAP

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [deptofdefense/dds.mil#375]
I noticed ya'll use Google Analytics; you might want to get added to DAP as well https://digital.gov/guides/dap/add-your-site-dap/

**Comment by jhackshaw-dds** [comment]
I believe we have DAP configured already. The DAP script is loaded [here](https://github.com/deptofdefense/dds.mil/blob/1a7f6883f5ea6c912b71ad38641a99f47326ea36/gatsby-ssr.js#L8) and pageview events are sent [here](https://github.com/deptofdefense/dds.mil/blob/1a7f6883f5ea6c912b71ad38641a99f47326ea36/gatsby-browser.js#L7). If we're missing anything else please let us know, thank you!

**Comment by its-a-lisa-at-work** [comment]
Ahh, didn't see that; awesome!
