### ISSUE TITLE
Update link for TDY to DDS

### ISSUE THREAD

**Issue by wclaymoody** [deptofdefense/dds.mil#53]
Currently the main index.html page for dds.mil has a button for "TDY to DDS" that links to the now defunct HireVue instance that was used in September and October of 2019.

Please adjust this link to send an email to Rebel at DDS just like the other Join button does. This will be a temporary fix until such time as a permanent applicant tracking system is implemented.

Here is a diff for this change:
```
diff --git a/src/index.html b/src/index.html
index e4426ea..7b31320 100644
--- a/src/index.html
+++ b/src/index.html
@@ -72,7 +72,7 @@ title: Defense Digital Service
       <div class="section-rule"></div>
       <h2>Our partners</h2>
       <p>We work alongside service members and civil servants across the Defense Department. DOD civilians and military members with technical expertise can apply to work with DDS on short-term details.</p>
-      <a class="join-button" href="https://dds.hirevue.com/signup/nCrKGCmnYGjYRFHKvmPAJX/">TDY to DDS</a>
+      <a class="join-button" href="mailto:Rebel@dds.mil">TDY to DDS</a>
     </div>
   </div>
 </section>
```

**Comment by ashhath01** [comment]
probably a good idea to start sizing this @vasavivempati93. the recruiting feature wont be around for a minute

**Comment by SCasarottoDDS** [comment]
This issue is no longer relevant. These links were updated previously but it looks like this issue was not closed.
