### ISSUE TITLE
PR checks not completing

### ISSUE THREAD

**Issue by jordangov** [deptofdefense/dds.mil#6]
The last two PRs I've submitted appear to be waiting on a status update from Travis, even though the CI processes appear to have completed successfully. See the screenshot below...

As an admin, I can bypass this and merge anyway, but we shouldn't need to.

![pr-waiting-for-checks](https://user-images.githubusercontent.com/30059011/47088251-04558280-d1ec-11e8-836c-a5664192bdec.png)

**Comment by SCasarottoDDS** [comment]
This was something @jhackshaw-dds and I discussed things related to this yesterday. We will make sure all the appropriate checks are handled and displayed for v2. Assigning to us to not let this slip by.

**Comment by jhackshaw-dds** [comment]
netlify build status are reflected for PR deploy previews and production deploys. Travis CI no longer in use.
