### ISSUE TITLE
Make changes to site after feedback is gathered

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#64]

**Comment by ashhath01** [comment]
After content has been given a pass make issues to ensure content change are completed by engineering/content/design/etc

**Comment by ashhath01** [comment]
some of this text is repetitive. consider updating: 
<img width="1301" alt="Screen Shot 2020-05-18 at 1 59 27 PM" src="https://user-images.githubusercontent.com/62910835/82262760-83162280-992f-11ea-8364-8b34bea13356.png">

**Comment by racheldds** [comment]
Adjusted copy under the 'Who We Are' and 'What We Do' bubbles in the blue ribbon for a little variety in language. Let me know of any questions. 

Also made one tweak to the copy in the R2D2 'Ongoing Technical Advice' section under 'Our Work' based on direct feedback from Brett L. via Slack.
