### ISSUE TITLE
Content check

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#67]

**Comment by ashhath01** [comment]
*A/C*
- go over what content we'll need now & then together

**Comment by racheldds** [comment]
Content rewrite: https://docs.google.com/document/d/1zqfVBnVzOERRV8qt5nDDkbv9dgH43TSkcZVpMdnNdzM/edit

**Comment by racheldds** [comment]
Thoughts: We need all content for first iteration — it can be watered down/cut down version of longer copy content, but we will at the very least need each of the "pages" noted within. 

These now include: 
1. ABOUT US	
2. OUR WORK
3. OUR TEAM	
4. ROGUE SQUADRON (Will need to be discussed with leadership; but I believe the last consensus was that we do want to fold RS website into ours vs. leave as standalone. Even if it's just linked on this "page" and then clicks out to their existing site that Savan worked to revamp during the merger.)	
5. MEDIA
6. JOIN US
7. LEGAL DISCLAIMER/CONTACT US/FOOTER LINKS (not a real page; just the footer/disclaimers)

**Comment by ashhath01** [comment]
@marieksmith fyi change to content noted here. adding marie to card for awareness
