### ISSUE TITLE
Netlify template research

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#68]

**Comment by ashhath01** [comment]
*A/C*
decision of what template we want to use that will allow us to:
  - get something up quickly
  - iterate over time
  - meets basic needs & resolves primary pain points

**Comment by marieksmith** [comment]
starting to look at templates here https://templates.netlify.com/

**Comment by marieksmith** [comment]
@vasavivempati93 
Looked at a handful of the templates from the netlify library, i think one of these would work as a possible starting point. They both have Netlify CMS & Blog page types built in, and decent layout to start with...

https://templates.netlify.com/template/middleman-starter/
https://templates.netlify.com/template/bluise-nuxt-cms/

**Comment by ashhath01** [comment]
decision made from 20.04.14 meeting:
- https://themeforest.net/item/jekyll-advance/23728497 is our suggested choice to start. looking into procurement solutions. 
- decision made b/c will accommodate lever, easy to get content in, we own netlify, responsive, has enough room to grow @vasavivempati93 @marieksmith feel free to comment if other pro's of this template

**Comment by ashhath01** [comment]
also support with paid template
looking at inspect element before procured

**Comment by ashhath01** [comment]
bought and paid. procured through cyndie. closing this.
