### ISSUE TITLE
Netlify recruitment tool integrations research

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#69]

**Comment by ashhath01** [comment]
*A/C*
- consider long term integrations for things like recruitment tool
- no immediate actions needed- but let's think about decisions now that will make our lives easier then
- document this reasoning either in this issue or somewhere else
  - development of best practices or anti patterns/anti-goals

**Comment by ashhath01** [comment]
@vasavivempati93 @marieksmith 
i'm cool closing this based on our discussions.
are there any best practices or anti patterns worth noting before i close?

**Comment by vasavivempati93** [comment]
i think it's good to be closed!

**Comment by ashhath01** [comment]
decision made: integrate lever
