### ISSUE TITLE
functionality one page

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#88]
based on marie's design functionality created for one page. expected hand off end of day 4/22

*acceptance criteria*
- link sent or posted here for us to see

**Comment by ashhath01** [comment]
@marieksmith tagging you here for awareness & handoff

**Comment by jhackshaw-dds** [comment]
Home page and about page:  https://v2-master--dds-mil.netlify.app/
Initial CMS: https://v2-master--dds-mil.netlify.app/admin
