### ISSUE TITLE
chore: decisions- design

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#90]
description:
- document thought process for any person picking this project up down the road

acceptance criteria:
- please document any decisions around design work including us web standards we're adhering to or choices made and why

**Comment by SCasarottoDDS** [comment]
@marieksmith I think would be great to keep decisions we make in a standard form (https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md) and then either held in a folder or in the wiki.

**Comment by marieksmith** [comment]
Yeah good call. I like the idea of adding to the gh wiki.

**Comment by SCasarottoDDS** [comment]
Yeah same. I think that is a good call. Let assume we put it there.

**Comment by marieksmith** [comment]
i did it!!!
https://github.com/deptofdefense/dds.mil/wiki/Documentation:-MVP-Design-Rationale

@ashhath01 added to gh wiki. closing this
