### ISSUE TITLE
chore: decisions- engineering

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#91]
this is to document our decision making in regards to technical reasoning.

*acceptance criteria*
- the languages and frameworks we'll be using and why
- best practices or guides to include
- any info for users picking this up without any background with chosen technologies

**Comment by SCasarottoDDS** [comment]
I think we should use something like this https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md to document our decisions. Thoughts on a folder with markdown files or should it be nested in the wiki?

**Comment by SCasarottoDDS** [comment]
Based on discussion in #90 lets try using GH wiki to keep this info.

**Comment by jhackshaw-dds** [comment]
ADR draft here https://github.com/deptofdefense/dds.mil/wiki/ADR:-Migration-to-Gatsby
