### ISSUE TITLE
design one page

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#92]
as discussed pick one page based on rachel's stack ranked content input & your decision of what should be built first

expected due date: 4/22 EOD

*acceptance criteria*
- handoff to jeff to begin building

**Comment by marieksmith** [comment]
here's a design start, in progress, still a lot to clean up and stuff, but a good start for theme.
- So far just Home & About Us for mobile & desktop
- This is using the USWDS system. For MVP let's roll with something basic like this, then a V2 can add "DDS SPICE" and elevate the design
- Home copy is placeholder (will need help from rachel... no rush)
- Photos/Icons also placeholder(ish)

Zee Designs:  
- See a prototype here: https://www.figma.com/proto/AE11xvBNxxNBck5mfZyOIy/MVP?node-id=1%3A2&scaling=min-zoom
- Get exported PNGs here: https://drive.google.com/drive/folders/1fHAnkxIk1Cvy6qr6s3Dvo1UiptxEP3_f

@ashhath01 @jhackshaw-dds
