### ISSUE TITLE
input content into homepage & about using cms

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#95]
acceptance criteria
- input content using netlify cms into new template
- note any feedback or thoughts to this issue for feedback for @jhackshaw-dds and @marieksmith 

(needs marie/jeff to finish their work first)

**Comment by racheldds** [comment]
Content input complete for 'Home' and 'About Us' — flagged tweaks/issues I saw with CMS and design to both Jeff/Marie via Slack. Updates currently in progress.
