### ISSUE TITLE
rectify netlify logins

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#96]
at the end of this milestone we should figure out what logins we need. 

questions/research needed:
- do content creators need separate logins or can they use the free netflify cms?
- do design/product folks need login or just engineering?
- if we do $45/month for three seats who are the three?
- how can we make sure the site is secure but people can login easily (1password shared vault?)

background of slack convo:
also- an ask over who should have an account for netlify. this is assuming an account is needed for content creators/recruiting. each additional seat is $15. we currently have three.
here is @cyndie’s suggestions. anyone have any heartburn or suggestions otherwise? feedback welcome. @cj - HR
@rachel -Comms
Ashley - product Manager
@jeff.hackshaw - Engineer
@marie - Designer
@cyndie - Billing

Only other suggestion would be to stick to 3 seats and keep them generic (unsure if this is possible, but thinking about future generations of DDSrs).
So, instead of individual accounts for 6 of us, do 3 general user logins:
1) content (for me, CJ, Marie)
2) admin (for Ash, Cyndie)
3) engineering (for Jeff)

And the logins could be housed in our 1pass DDS vault so that we never have to go searching for login credentials again.

we can change the accounts as people come and go.

^i’m ok with this. only hiccup might be authentication is a pain in the ass with shared folks. how much do we care about budget on this?

we’re okay with the cost. The number of seats can be increased or decreased at any time since it’s a monthly bill.

ok. so it’s no stress then i’m cool with your suggestion @cyndie

After setting some initial stuff up, I don't think everyone would need netlify (hosting) accounts. netlify-cms is free and a separate thing. In order to write content you would log into netlify-cms with github credentials and write there. I haven't gotten there yet, but I think the same would apply for lever - you would write/post content on their platform, not through netlify.

**Comment by ashhath01** [comment]
decision:
we're going to keep three seats. will add another story for @SCasarottoDDS  & @CynVieira  to pair and sort things out. right now the three seats will be saved for a general use item and someone in these roles
- admin 
- engineering
- ? etc

**Comment by CynVieira** [comment]
Yes.  I am here for this.

**Comment by ashhath01** [comment]
accounts have been trimmed down. current users jeff/cyndie/stuart. 3 seats.

**Comment by ashhath01** [comment]
@CynVieira double checking- have we downgraded since we've removed seats?

**Comment by CynVieira** [comment]
We downgraded the seats to 3, Orders (parent account of DDS needs a seat), Stu and Jeff since users can log in using their github accounts. Stu has more information on how to log in using Github.
